version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  
jobs:
  build-backend:
    working_directory: ~/my-google-service/Backend
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: jelovceva
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: my-google-service

    steps:
      - checkout:
          path: ~/my-google-service
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

  build-frontend:
    working_directory: ~/my-google-service/Frontend
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout:
          path: ~/my-google-service
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: build
          command: |
              npm run build
            
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  build:
    jobs:
      - build-backend
      - build-frontend
      
      - heroku/deploy-via-git:
          name: deploy-back
          app-name: my-google-service-api
          filters:
            branches:
              only:
                - main
          requires:
            - build-backend
            
      - heroku/deploy-via-git:
          name: deploy-front
          app-name: my-contacts-photos-service
          filters:
            branches:
              only:
                - main
          requires:
            - build-frontend
            - deploy-back 